[[redirects]]
from = "/api/"
to = "https://warm-macaron-817d9b.netlify.app:/splat"
status = 200
force = true
headers = {X-From = "Netlify"}
[[headers]]
for = "/"
[headers.values]
Access-Control-Allow-Origin = "*"